name: Publish MDNEXT Templates

on: push

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/hub-create-repos
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      - name: publish:starters
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: templates domitriusclark 
